### ISSUE TITLE
for-loop to format imported peaks data

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/nmrrr-workflow#1]
peaks data are split into multiple groups of the 9 columns.

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/50244730/111732139-2971d380-8832-11eb-804d-5b021b037d97.png">

trying to set up a for-loop to iteratively pull 9 columns at a time, and then rbind them.

https://github.com/kaizadp/nmrrr/blob/76028ef2ff6fbd36255e124bcefcd541a3c004fe/code/functions.R#L8

**Comment by bpbond** [comment]
While `for()` works perfectly well, I ended up using `lapply()` in #2 .
